# Generated by Django 3.1.3 on 2021-05-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Adress', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=30)),
                ('Product_name', models.CharField(max_length=30)),
                ('Flavor', models.CharField(max_length=30)),
                ('Subscribed_date', models.DateField()),
                ('Subsciption_end', models.DateField()),
            ],
        ),
    ]
