# Generated by Django 3.1.3 on 2021-05-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=30)),
                ('Last_name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=30)),
                ('Adress', models.CharField(max_length=100)),
                ('Product_name', models.CharField(max_length=30)),
                ('Flavor', models.CharField(max_length=30)),
                ('Subscribed_date', models.DateField(max_length=30)),
                ('Subsciption_end', models.DateField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='Flavor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Product_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Subsciption_end',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Subscribed_date',
        ),
    ]
