# Generated by Django 3.1.3 on 2021-05-06 19:27

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210506_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('image', models.FileField(upload_to='')),
                ('flavor', multiselectfield.db.fields.MultiSelectField(choices=[('f1', 'Flavor1'), ('f2', 'Flavor2')], max_length=5)),
            ],
        ),
    ]
