# Generated by Django 3.1.3 on 2021-05-06 20:21

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='flavor',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Flavor1', 'Flavor1'), ('Flavor2', 'Flavor2')], max_length=15),
        ),
    ]
