# Generated by Django 3.1.3 on 2021-05-06 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210507_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Subsciption_end',
            new_name='Subscription_end',
        ),
    ]
